# Generated by Django 4.0 on 2022-01-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changeblog', '0003_category_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='site',
            field=models.CharField(default='king_casino', max_length=255),
        ),
    ]
