# Generated by Django 4.0 on 2022-01-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changeblog', '0004_site_post_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='site',
            field=models.CharField(default='King Casino', max_length=255),
        ),
    ]
