# Generated by Django 4.0 on 2022-01-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changeblog', '0007_alter_post_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(default='Public', max_length=255),
        ),
    ]
